### ISSUE TITLE
RC will slow game at some point

### ISSUE THREAD

**Issue by hexophile** [hexophile/crawl#9]
To prevent this RC need better management in autochange tile.

EDIT: Autochanging player tile is slow, need replacement or better solution.
Proposed solution: Write function that will check player for XL upping and calls AutoChangeTile() function

**Comment by Pipeliner** [comment]
You probably want to save current tile in some global variable and only use `tile_player_tile` if new tile is going to be different than the saved one.

**Comment by hexophile** [comment]
Yeah, I'll think about it this night. Also I can't assignee two people to one issue, so you can think about it as well :)

**Comment by hexophile** [comment]
Fix: https://github.com/hexophile/crawl/commit/4cbcd88c955b02d5b1632149d24eef30603b510b

**Comment by Pipeliner** [comment]
Looks reasonable, did this help?

**Comment by hexophile** [comment]
I'm not sure, we can always find out when we add more options in AutoChangeTile() function.
But it's better to check tile every new XL than every step anyway.
